### PR TITLE
Updated campfeessupplement.json

### PR DESCRIPTION
**Pull request by tekarrawilkinson**
Adding campfeessupplement.json.

Review: https://brms-simulator-dev.apps.silver.devops.gov.bc.ca/rule/66bcfcec7ddfdc3c0c025913?version=inReview

### CODE REVIEW

**Comment by brysonjbest** [comment]
@sbuhovac Testing Examples Ready
[general-supplements_campfeessupplement.csv](https://github.com/user-attachments/files/16880790/general-supplements_campfeessupplement.csv)

**Review by Iliana777 — DISMISSED** [review]
just noticed that this rule does not ask whether assistance is in pay. MSO clients have  PWD designation but assistance is not in pay so they are not eligible for camp fees

**Review by Iliana777 — COMMENTED** [review]
In Pay has been added but not tested yet.

**Comment by tekarrawilkinson** [comment]
[general-supplements_campfeessupplement (2).csv](https://github.com/user-attachments/files/16899792/general-supplements_campfeessupplement.2.csv)
2nd version of testing scenarios including InPay as per Iliana's comment

**Review by prchristenson — COMMENTED** [review]
Under the Eligibility rule:  "is dependent" should be changed to "is dependent child".  Only dependents that are **children** can be eligible for camp fees.

**Comment by tekarrawilkinson** [comment]
current state works, future state will require utility rules surrounding age in regard to "isDependentChild" and how that interacts with other fields with age requirements, re: "hasPWDDesignation"

**Comment by sbuhovac** [comment]
I just ran a simulation and it approved a negative amount. How are we dealing with negative amounts in BRE simulation?

**Comment by tekarrawilkinson** [comment]
> I just ran a simulation and it approved a negative amount. How are we dealing with negative amounts in BRE simulation?

@sbuhovac this has been corrected

**Comment by sbuhovac** [comment]
> > I just ran a simulation and it approved a negative amount. How are we dealing with negative amounts in BRE simulation?
> 
> @sbuhovac this has been corrected

It doesn't allow a negative number anymore.

**Comment by tekarrawilkinson** [comment]
[general-supplements_campfeessupplement_testing_Updated_Test_Scenarios_2024-09-10T16-51-26Z.csv](https://github.com/user-attachments/files/16949478/general-supplements_campfeessupplement_testing_Updated_Test_Scenarios_2024-09-10T16-51-26Z.csv)
@sbuhovac @rachel0728 I have added what I think are the relevant scenarios. can you check these?

**Comment by rachel0728** [comment]
I would add one for already received in the fiscal year for both adult and dep.

**Comment by sbuhovac** [comment]
> [general-supplements_campfeessupplement_testing_Updated_Test_Scenarios_2024-09-10T16-51-26Z.csv](https://github.com/user-attachments/files/16949478/general-supplements_campfeessupplement_testing_Updated_Test_Scenarios_2024-09-10T16-51-26Z.csv) @sbuhovac @rachel0728 I have added what I think are the relevant scenarios. can you check these?

These scenarios look good to me. My only question is this: if the requested amount is zero should the eligible output still be TRUE. I understand all variables are matching the correct row so the Eligible output should be TRUE but in reality we don't say someone is eligible for a supplement if the requested amount is zero.

**Comment by rachel0728** [comment]
@sbuhovac I agree on the scenarios.

**Review by Iliana777 — COMMENTED** [review]
@tekarrawilkinson @prchristenson I added two scenarios and both passed. Would it be possible for the inputs to be listed in the same order as in the map? We will have to get more intentional as to the input order in the maps as well. For this one, asking if it is for a dependent child may be best right after asking if the recipient has PWD designation.

Also, noticed that we do not address 'is funding exhausted' in the map (we will have to update). Good catch here.

**Comment by prchristenson** [comment]
@tekarrawilkinson @Iliana777 Suggest changing "is funding exhausted" to "is supplement budget exhausted" to be more clear.  Would like to have a conversation to confirm where we landed on whether we can include a rule that asks if prioritization is required.  There is an active discussion in the [FigJam map] about this (https://www.figma.com/board/RQWEi0AcOPAweRURkenYUN/Camp-fees-supplement-(monetary)?node-id=42-739&node-type=section&t=I472CHqkra71c9dE-0)

**Comment by tekarrawilkinson** [comment]
@Iliana777 @prchristenson I updated the input and organized the order differently. I've sent you message in teams with more detail as some of this may need a discussion.

**Comment by Iliana777** [comment]
@tekarrawilkinson I added three tests: Supplement has been paid, Budget exhausted and Prioritization required. The first two passed but the prioritization test failed. 
Also, the CSV spreadsheet does not list the results for all the previous tests. Is that correct?

**Comment by prchristenson** [comment]
@brysonjbest @tekarrawilkinson  My validation testing resulted in the same failure error as @Iliana777 .  See Scenario #15: Prioritization Required but not Met. Result was a "TRUE" for eligible when we are expecting a "FALSE".

**Comment by brysonjbest** [comment]
> @brysonjbest @tekarrawilkinson My validation testing resulted in the same failure error as @Iliana777 . See Scenario #15: Prioritization Required but not Met. Result was a "TRUE" for eligible when we are expecting a "FALSE".

fixed

**Comment by prchristenson** [comment]
@tekarrawilkinson Validation Testing Complete.    @sbuhovac @rachel0728 Camp Fees rule is ready for Isolation Testing.

**Review by prchristenson — APPROVED** [review]

**Review by Iliana777 — APPROVED** [review]
'Prioritization required but not met' test passed. Validation testing completed.

**Comment by sbuhovac** [comment]
[general-supplements_campfeessupplement_testing_Published_general-supplements_campfeessupplement_2024-10-01T18-31-58Z.csv](https://github.com/user-attachments/files/17214423/general-supplements_campfeessupplement_testing_Published_general-supplements_campfeessupplement_2024-10-01T18-31-58Z.csv)

@rachel0728 and I completed isolation testing with all tests passed.

**Review by sbuhovac — APPROVED** [review]

**Review by rachel0728 — APPROVED** [review]
Review completed with Sasha; all tests passed

**Pull request merged**
