### PR TITLE
Updated guidedogsupplement.json

### PR DESCRIPTION
**Pull request by brysonjbest**
Adding guidedogsupplement.json for review.

Review: https://brms-simulator.apps.silver.devops.gov.bc.ca/rule/6670c8499c32057b791a890b?version=inReview&_=1729021006080

### CODE REVIEW

**Comment by Iliana777** [comment]
@brysonjbest Would it be possible to update the language in the rule so we follow the language in the PPM? i.e. guide/service/retired dog vs guide dog only and eligible for up to two months vs two month eligibility. @prchristenson may have some suggestions.

I ran two tests. The 'Does not use guide dog' test failed even though the expected result (false) was correct; however, I entered the supplement amount as $0 and entered false for twoMonthEligibility. I assume that it failed because I did not leave those fields blank.

**Comment by brysonjbest** [comment]
@Iliana777 For sure we can update the language! Any suggestions on where exactly and how you'd like that changed? Is it in the inputs/outputs, or the rule components? @prchristenson Wording would be appreciated for any changes. 

Regarding the test, yes it shows as failed because those other fields were given values. Currently the rule does not return a supplement amount or twoMonthEligibility if the family is found ineligible. This currently considers that this is the only relevant value - that someone is ineligible, as there would therefore be no twomontheligiblity or supplement amount. I've updated the test to pass.

**Comment by prchristenson** [comment]
@brysonjbest 

@Iliana777 and I have some items that need to be discussed before we can complete the validation testing on this rule set.  I've set up a 1/2 hr mtg for a rule walk through with you, Amanda & us Validator SMEs.   Some notes are in the [map] (https://www.figma.com/board/pzl4SE8BZgtMvCayu8FZbd/Guide-dog-%26-service-dog-(monetary)?node-id=1-2002&node-type=shape_with_text&t=Juj8m2CgsyUnvsku-0)

Sharing these items here so we have a place to start: 

1. The order of the inputs under "simulate manual inputs" doesn't quite make sense to us making the difficult to test and assess if the rule is built correctly.  
2. We believe using 'Number of Recipients' as a testing input is confusing.  What we need to enter is the number of people on the case that use a guide or service dog to establish the number of guide or service dog teams.  Once we have that as an output, then we can move to the Supplement Calculation table.
3. Minor edit an output: Change 'Two Month Eligibility' to 'Up To Two Months of Eligibility' 
4. Would using the Description section of the table be helpful for scenario development?
5. Can we eliminate the option to enter 0 under Expected Results for those items that should be entered as a binary answer (true/false)?  This would reduce some of the tests from failing.

**Comment by brysonjbest** [comment]
> @brysonjbest
> 
> @Iliana777 and I have some items that need to be discussed before we can complete the validation testing on this rule set. I've set up a 1/2 hr mtg for a rule walk through with you, Amanda & us Validator SMEs. Some notes are in the [map] (https://www.figma.com/board/pzl4SE8BZgtMvCayu8FZbd/Guide-dog-%26-service-dog-(monetary)?node-id=1-2002&node-type=shape_with_text&t=Juj8m2CgsyUnvsku-0)
> 
> Sharing these items here so we have a place to start:
> 
>     1. The order of the inputs under "simulate manual inputs" doesn't quite make sense to us making the difficult to test and assess if the rule is built correctly.
> 
>     2. We believe using 'Number of Recipients' as a testing input is confusing.  What we need to enter is the number of people on the case that use a guide or service dog to establish the number of guide or service dog teams.  Once we have that as an output, then we can move to the Supplement Calculation table.
> 
>     3. Minor edit an output: Change 'Two Month Eligibility' to 'Up To Two Months of Eligibility'
> 
>     4. Would using the Description section of the table be helpful for scenario development?
> 
>     5. Can we eliminate the option to enter 0 under Expected Results for those items that should be entered as a binary answer (true/false)?  This would reduce some of the tests from failing.

@prchristenson  and @Iliana777 Updated inputs and outputs.
1&2: Updated to replace number of recipients with more specific numberOfDogTeams.
3: Updated to 'Up to two months of eligibility'.
4: Updated eligibility table with descriptions.

Discussed use of expected results field and editing/deletion of scenarios. Maintaining current behaviour for now as per discussion.

**Comment by prchristenson** [comment]
@brysonjbest  @Iliana777   I ran some more validation tests and came up with a scenario that we have not accounted for in the rule:  1 person with two dogs - one is certified as retired and the other is pending certification and has a test booked at JIBC.  The contact on the case is part of two dogs teams but with different documentation types.    

One other update to the language used in the description for "Certification" in the Eligibility Table.   Based on info from the GDSD certification website, the accepted documentation to prove certification is either:
1) A valid Guide Dog and Service Dog Act (GDSDA) Certificate issued by the Registrar of Guide Dogs and Service Dogs OR
2) A valid identification (ID) card issued by an accredited training school.

I've left a note in the both the rule map and in the Hive (discussion page) for follow up actions re certification docs.

**Comment by brysonjbest** [comment]
@prchristenson @Iliana777 Updates made to the supplement to handle any number of guide dog teams, as there is no technical limit. Different dog teams can now have different types of documentation. If any one dog team for the individual has a test booked (is not certified yet), the 'up to two months eligibility' status will return as true - meaning the individual is flagged for that review even if they have another dog team that is 'certified'. 

Added some notes in the rule explaining the process as it has changed. Also updated the description field, though it has now been moved to the 'eligible dog teams' table.

Let me know if you'd like to discuss the new implementation or if you have any questions or concerns.

**Comment by Iliana777** [comment]
@brysonjbest @prchristenson I ran a simple validation test and received the correct result. However, I am wondering if it would be possible to receive a result for each dog team? So if one is certified, the result would be eligible without the 'up to two months' restriction and if another has a test booked, it would be eligible with the 'up to two months' as true. Just thinking that the certified dog is eligible ongoing and should not have to go through being reassessed for eligibility once the other dog is tested.

**Comment by brysonjbest** [comment]
@Iliana777 @prchristenson I did think about this approach, but I was wondering how this was applied practically. Are individuals with multiple dogs recorded having each individual dog? Is each dog tracked separately in practice, and multiple supplements are provided? Or is only one supplement provided with an expiry of two months, for the total of the guide dogs, and it is manually reinstated/partially issued if a dog is no longer eligible?

Would having 'Up to two months' be returned as a number make more sense? In this situation, hypothetically, if there are 4 guide/service animals, and three are pending tests, 'Up to two months' would return '3', and this number would be used to determine how many of the supplements to end date for 2 months? Currently dogs do not have their own ID that I am aware of that we would use to track them and their certification progress.

Let me know what you think and I can draft a version with potential changes.

**Comment by prchristenson** [comment]
> @brysonjbest @prchristenson I ran a simple validation test and received the correct result. However, I am wondering if it would be possible to receive a result for each dog team? So if one is certified, the result would be eligible without the 'up to two months' restriction and if another has a test booked, it would be eligible with the 'up to two months' as true. Just thinking that the certified dog is eligible ongoing and should not have to go through being reassessed for eligibility once the other dog is tested.

I ran a test as well and it passed (saved it to the scenarios).  This rule passes but will limit the $190/mo payment to two months so wondering how that next step of confirming certification of the second dog is managed?  Is it a business process or part of the rule?

**Comment by Iliana777** [comment]
@brysonjbest @prchristenson I confirmed with @sbuhovac that there is a maximum limit set in MIS for this supplement (code 09) to $95. It cannot be issued twice in the same month. We have to decide if we build the rule as current state or to be able to accommodate multiple dog teams (I don't know how this is being done now).
To your comments: I like the idea of 'Up to two months' return a number (if we decide to build the rule to accommodate multiple dog teams) and, I agree Pam, confirming certification of a dog would be a business process.

**Comment by sbuhovac** [comment]
Currently, MIS restricts Code 09 to a fixed rate of $95 per case. And as such, only one person in a family unit can be provided code 09. ICM OIA does not appear to have any such restrictions so all the limations are coming from MIS.

**Comment by prchristenson** [comment]
> @brysonjbest @prchristenson I confirmed with @sbuhovac that there is a maximum limit set in MIS for this supplement (code 09) to $95. It cannot be issued twice in the same month. We have to decide if we build the rule as current state or to be able to accommodate multiple dog teams (I don't know how this is being done now). To your comments: I like the idea of 'Up to two months' return a number (if we decide to build the rule to accommodate multiple dog teams) and, I agree Pam, confirming certification of a dog would be a business process.

As the policy allows the supplement to be issued for both active and retired dog teams, we need to build it to allow for multiple payments @$95 per dog/per month.   Currently, I believe staff have to run assisted eligibility for each dog, so I think we need to do the same in the BRE and have independent outputs for each dog team. If built this way, ICM will need allow for wo benefit lines on the contact/case.   If there is an active guide dog team that is pending certification (test booked) the rule should restrict that benefit line payment to be 2 months of payments.  If that needs to be extended due to the dog failing the JIBC test, then the recipient would need to submit a new request for another 2 months of the supplement.  Does that work?

**Comment by brysonjbest** [comment]
@Iliana777 @prchristenson @sbuhovac 
If the guidedogsupplement is issued in the way that @prchristenson indicates, then I believe removing the # of dog teams entirely is required. As with other supplements that are run on a 'per-person' basis, this would be considered to be run on a 'per-dog' basis - returning the desired outcome per dog this rule is run against. As we are unsure of how handling multiple dog teams is done in practice, this brings the rule down to the smallest level of granularity for now. It can then be expanded in the future to address specifics of this case.

I have maintained the previous scenarios, as I don't want to delete them until we are sure this is the direction we're going, but I have added 4 new scenarios to the bottom of the list that address the main situations of this rule.

Let me know what you think of the revised rule, and either delete the old scenarios or let me know if it's okay to do so.

**Comment by brysonjbest** [comment]
@Iliana777 @prchristenson 
Revisions made to separate out the guide dog supplement from the temporary supplement for test booked. Please let me know your thoughts and if you'd like to chat about it.

**Review by Iliana777 — APPROVED** [review]
I ran two tests (and saved them) and both passed as expected. I appreciate having a record of the discussions we had for this rule to remember what we worked through. Approving rule.

**Comment by prchristenson** [comment]
@brysonjbest Are you able to update the documentation input from "certification" to "certifiedActive" to match the "certifiedRetired" format?   Let me know if there were any other changes to the rule from our previous 2 discussions.  If not, I'll complete my final validations.

**Comment by brysonjbest** [comment]
@prchristenson Updated naming conventions to use input of certifiedActive. I believe that other potential changes from our discussions were addressed, but if there's anything I've missed please let me know!

**Review by prchristenson — APPROVED** [review]
Validation testing completed - Approving Rule.  @brysonjbest Ready to send to Isolation Testing.  

Attached Scenarios CSV.  
[general-supplements_guidedogsupplement (1).csv](https://github.com/user-attachments/files/17650584/general-supplements_guidedogsupplement.1.csv)

**Comment by brysonjbest** [comment]
Reviews completed for Validation Testing. @sbuhovac @rachel0728  Tagged for reviews of isolation testing.

**Review by sbuhovac — APPROVED** [review]
Isolation testing passed.
[general-supplements_guidedogsupplement_testing_guideDogDocumentatio_certifiedActive__guidedogsupplement.json_2024-11-08T18-20-47Z.csv](https://github.com/user-attachments/files/17683019/general-supplements_guidedogsupplement_testing_guideDogDocumentatio_certifiedActive__guidedogsupplement.json_2024-11-08T18-20-47Z.csv)

**Review by rachel0728 — APPROVED** [review]
isolation testing passed as per @sbuhovac

**Pull request merged**
