### PR TITLE
Updated da-support.json

### PR DESCRIPTION
**Pull request by brysonjbest**
Updated precedence of family compositions to correctly return amounts for spouse >= 65. 
Review: https://brms-simulator.apps.silver.devops.gov.bc.ca/rule/667dbf216e28561595e73642?version=inReview&_=1728316438392

### CODE REVIEW

**Comment by sbuhovac** [comment]
We re-tested and found one more error in isolation testing (see attached spreadsheet). 

Also, we reviewed the DA table and found 5 rows in total that don't fully correct variables setup (e.g. PWD can be any age but the table restricts to under 65 in a row). Only one of the 5 rows can result in a failed test. The other 4 cannot result in a failed test because the same family unit shows up earlier in the table with the correct result. Those 4 rows are incorrect nevertheless, and if you move them at the top of the table, they would result in failed tests.

@brysonjbest please review

[table-DA.xlsx](https://github.com/user-attachments/files/17299380/table-DA.xlsx)
[support-shelter_da-support_testing_Published_support-shelter_da-support_2024-10-08T20-34-44Z.csv](https://github.com/user-attachments/files/17299381/support-shelter_da-support_testing_Published_support-shelter_da-support_2024-10-08T20-34-44Z.csv)

**Comment by rachel0728** [comment]
Reviewed with @sbuhovac see his comment for our results.

**Review by prchristenson — CHANGES_REQUESTED** [review]
The rule is not running correctly for Couples w 1PWD & 1non-PWD.  I think it's related to lines 6 and 7 in the calc table.  The age of the person with PWD is does not impact the rate but the age of the non-PWD (<65 vs =>65) does affect the rate.  A person with PWD can be over 65 and still be eligible for disability assistance.

**Comment by brysonjbest** [comment]
Updated rule to be age agnostic for PWD and more clear in path followed. Attached passing tests.
[Revised Passing DA Support.csv](https://github.com/user-attachments/files/17315792/Revised.Passing.DA.Support.csv)

**Review by prchristenson — APPROVED** [review]

**Comment by Iliana777** [comment]
@brysonjbest I simulated a scenario with a 7 year old non-PWD and a 10 year old with PWD and received the amount of $1478.50 which is the correct amount if they were adults and the non-PWD is under 65 but the result should be 0 as both are children. PWD have to be at least 18 and non-PWD have to be at least 19.

**Comment by brysonjbest** [comment]
> @brysonjbest I simulated a scenario with a 7 year old non-PWD and a 10 year old with PWD and received the amount of $1478.50 which is the correct amount if they were adults and the non-PWD is under 65 but the result should be 0 as both are children. PWD have to be at least 18 and non-PWD have to be at least 19.

Just as with the IA Support rule, this rule is not age gated for eligibility purposes. These rules are calculating the maximum support amount based on the rate tables that are available for support. Age is included in this rule as an input only because the maximum support rate differs dependent on if someone is >= 65. If the rate didn't vary for family units with members >= 65, age would not be relevant. The actual eligibility for disability assistance is not determined by this rule, but would be handled by another rule, and the appropriate persons/ages would be passed on to this rule for determining maximum rate. This is a support rate calculation only.

**Review by Iliana777 — APPROVED** [review]
Scenarios ran passed. Thank you @brysonjbest for the reminder that other utility rules will provide the eligibility for disability assistance. Approved.

**Review by sbuhovac — APPROVED** [review]
[support-shelter_da-support_testing_Published_support-shelter_da-support_2024-10-11T18-58-26Z.csv](https://github.com/user-attachments/files/17347418/support-shelter_da-support_testing_Published_support-shelter_da-support_2024-10-11T18-58-26Z.csv)

Isolation tests re-tested and they all passed. On that ground, I approve this pull request.

To be noted, I still disagree with the table design, as discussed, but since all tests passed in the current table setup, I have no further comments.

**Comment by brysonjbest** [comment]
Updated with extended descriptions for all table items that match their policy rate table descriptions.

**Comment by rachel0728** [comment]
Reviewed as per Sasha's comment.

**Comment by rachel0728** [comment]
Review completed as per Sasha's comments.

**Review by rachel0728 — APPROVED** [review]
Approved as per Sasha's comments.

**Pull request merged**
