### PR TITLE
Updated comforts-allowance.json

### PR DESCRIPTION
**Pull request by tekarrawilkinson**
Adding comforts-allowance.json.

Review: https://brms-simulator.apps.silver.devops.gov.bc.ca/rule/66cf6b951aeab403143d691a?version=inReview

### CODE REVIEW

**Comment by rachel0728** [comment]
Review complete

**Comment by Iliana777** [comment]
@brysonjbest When I go to Simulate manual inputs, there is only an empty box, there are no questions/criteria listed?

**Comment by brysonjbest** [comment]
@Iliana777 The inputs and outputs have been added and you should be able to run simulations now! In order to maintain similar structure with already existing inputs/outputs in Klamm, I did make some changes to the rule @tekarrawilkinson, so re-validation may be required to ensure that it is still working as intended. Please let me know if you have any questions.

**Comment by Iliana777** [comment]
@brysonjbest I ran a few scenarios and saved two that did not pass but I think I got confused with the two questions (isLongTermFacility and residingInCareFacility). Suggesting different wording for the isLongTermFacility question - 'going into a facility on a long term basis' @prchristenson thoughts?
We need to specify if the person going into the facility has the PWD designation. 
I see there is supposed to be an output for Is Case Separation Required but I did not see it when I ran the tests?

**Comment by brysonjbest** [comment]
@Iliana777 @prchristenson I've updated this to have the other two scenarios pass.

Regarding isLongTermFacility, I'd named the variable this way to describe the type of facility that an individual is entering to match the current version of the figma map.

Regarding specifying that an individual has the PWD designation, the rule is specifically regarding the singular individual going into a care facility - and therefore the hasPWDDesignation property is always about the individual going into the facility. Further specifying it on the rule shouldn't be necessary. 

Case separation reason should now be returned only in cases where the individual is going into a long-term care facility, is otherwise eligible, but has a family unit size greater than 1.

**Comment by Iliana777** [comment]
@brysonjbest @prchristenson I ran three tests:

1. Family not in pay - it failed because I left the expected amount result blank. Otherwise, I did get the expected result of 'false'. In the Guide Dog rule, the opposite (entering 0 in the expected result) made the test fail. I understood that in order for the test to pass, we were going to leave the expected amount blank?
2. Family member entering LTC - it failed because I left the reason blank
3. Family member entering LTC v2 - it failed because the reason I entered did not match the reason provided. It looks like the reason has to match exactly in order for this test to pass.

We will have to revisit the figma map to update the language. 
Thank you for explaining that further specifying that an individual has PWD designation is not necessary - it makes sense.

**Comment by brysonjbest** [comment]
@Iliana777 @prchristenson 

1. I've updated the rule and resubmitted it, so now the test passes where no supplement amount is given. This matches the other guide dog rule. 
2 & 3 - If any part of the expected results are filled out, then the system is seeing it as those results **exactly** are what is expected. So if you leave the reason field blank, but fill in any of the other fields, it will return as wrong as the reason is not blank. Additionally, as you mention in 3, the reason it failed was due to it not matching exactly. Tests are very specific in their matching in order to make sure nothing slips through by accident or by partial match.

**Comment by sbuhovac** [comment]
Case separation is only required when one spouse goes to LTC and the other remains at home. However, there are scenarios where both spouses go to the same LTC so they need to remain on the same case, and we issue Comforts to both. The rule needs to accomodate both scenarios.

**Comment by brysonjbest** [comment]
@prchristenson @Iliana777 
Updated with new comforts that does not require case separation for couples. Please review and connect with any questions or concerns.

**Comment by Iliana777** [comment]
@brysonjbest @tekarrawilkinson I ran and saved 2 tests (FU 1 in facility but not LTC and FU 1 not in facility). Both passed. 
Feedback: 
1. The order of the questions/inputs is confusing as we are asking if it is a long term care facility first, then PWD status, then residing in care facility. We should ask: family in pay, family size, residing in care facility, is it a long term care facility, then PWD status.
2. If it is a couple, how do we identify if one is staying home? I looked at the map and case separation is listed as a utility rule so I am not sure if we need to include it in this rule? 
3. How do we identify if both are going into the same facility as per @sbuhovac comment re: both receiving comforts?

**Comment by brysonjbest** [comment]
@Iliana777 @tekarrawilkinson 
1. The order of inputs is alphabetical. This is the default for all rules. If a custom sort order was required, this would be a development change, and a custom sort order would have to be decided on and defined for each individual rule. Important to note is that the order of questions for frontend users in ICM would not be the same as what is displayed on a rule. Rules are agnostic to the order in which they receive all the input variables necessary to process. We could also change the input names on this rule if you'd like to align with the current alphabetical sort? 'Residing In Care Facility ' -> 'Is Residing in Care Facility', and 'Is a Long Term Care Facility' -> 'Is the Facility Long Term Care'. Please let me know if this is desired.
2. As you mentioned, case separation is a separate rule. This current rule only handles the calculation for the final family unit size being passed in. Case separation would be decided before this rule, and the final family composition passed into this rule. The descriptions in the 'Supplement Calculation' table detail the different situations this rule is tailored for.
3. The description fields in the 'Supplement Calculation' table handle both going into a facility together. If individuals in a family unit were going into separate facilities, or only one going in, their assessment would not reach this rule, as a 'Case Separation' requirement would have been decided by a 'Case Separation' utility rule prior.

**Comment by Iliana777** [comment]
@brysonjbest @tekarrawilkinson Thank you for the clarification, Bryson. 
1. Good to know about the alphabetical order of inputs. I like your suggestion of updating the input names so they align with the alphabetical sort. I would like @prchristenson input on this.
2. & 3. Thank you for the clarification. The descriptions are clear. It makes sense now.

**Comment by prchristenson** [comment]
@brysonjbest @tekarrawilkinson  
1.  Discussions on Nov 8th with Bryson and Iliana.  Decision to remove 'Is a Long Term Care Facility' as an input for this base eligibility rule for comforts allowance as eligibility for comforts allowance is not contingent on the special care facility being a LTC facility.  That variable will be needed in the associated rule related to case separation which is still to be built).  
NEW ISSUE:  
2. Ran new set of validation testing (saved).  All passed except one. Currently the rule is not allowing for payment of comforts for more that 2 family members; however, in some situations, a child may accompany their parent/s into a special care facility.  MIS and ICM were updated to accommodate this scenario in 2023.   Should this be added to this rule or handled under a different child rule?

**Comment by brysonjbest** [comment]
@prchristenson @tekarrawilkinson 
Regarding this new issue, we can definitely update it to accept family unit sizes greater than 2. Currently it was built with the concept that children are not included in this calculation at all. Do the rates change for the family size in these instances? Are the children provided the 115 per child? For example, in a family composition of one non-pwd parent, and two children going into a facility together, would that be 115 * 3 = 345?

**Comment by Iliana777** [comment]
@brysonjbest @prchristenson @tekarrawilkinson 
Correct, Bryson. The comforts rate for children is the same as the rate for an adult without PWD = $115

**Comment by brysonjbest** [comment]
@tekarrawilkinson @prchristenson @Iliana777 
Fantastic! I have updated the rule to reflect other family sizes and compositions for testing, with the aforementioned scenario now passing.

**Review by prchristenson — APPROVED** [review]
Added new scenario to test code change -> Single parent going into a facility with a child (FU 2, 1PWD, 1non-PWD (child) which passed.  My validation testing is complete - Rule Approved.

**Review by Iliana777 — APPROVED** [review]
I added one scenario (FU 4, 1 PWD adult, 3 children in facility) and it passed. Approving pull request.

**Comment by tekarrawilkinson** [comment]
@sbuhovac @rachel0728 this rule is now ready for isolation testing for Sprint 15. let me know if you have any questions.

**Comment by sbuhovac** [comment]
Input "Family Unit Size" is used across other rules to refer to the total number of active family members. If that is what it means in this Comforts rule, then the rule needs to be updated to specify who in the family is in facility and who isn't. If the input refers to only family members who are in facility (rather than the total number of family members), then the input label needs to be updated to mean specifically that.

**Comment by brysonjbest** [comment]
@sbuhovac 
I've updated the family unit size input to more accurately reflect how we are currently using it across the rule base. Here is the new description, also available in KLAMM for review:
"The number of people in a family unit to be considered for a specific calculation. Family unit size is a calculated value. The calculated number of people in a family unit for this field may differ depending on the specific requirements of the supplement or circumstances being assessed, and therefore can include some, or all, active members of a family unit."

This new description captures the calculated nature of the familyunitsize input. In this rule specifically, the family unit size coming into the calculation is only for those individuals who are going into a facility. This is the same logic applied to the existence of 'person2pwdstatus' on this rule - where this is only filled out for a family unit that is entering the facility together. As discussed above, the 'case separation' rule would run prior. Additionally, a 'family composition' rule would be responsible for calculating the 'familyunitsize' input amount prior to it being processed by this rule, which is the ultimate calculation of the maximum rate of comforts for the members of a family unit entering a facility.

**Comment by tekarrawilkinson** [comment]
@brysonjbest @sbuhovac based on our conversation this morning, I have an idea about better differentiating between the familyunitsize input and what it means. I could change it to something like `EligibleFamilyUnitSize` if its calculating per rule(with the updated definition above) and then `TotalFamilyUnitSize `if its referring to count the entire family unit? Might make this more clear, open to suggestions.

**Comment by brysonjbest** [comment]
@tekarrawilkinson @sbuhovac 
I'm not sure when we would be needing to differentiate between these right now, as familyUnitSize is a calculated variable. The Total Family Unit Size, referring to the full entire family unit would also just be the same calculated variable for whenever that number is actually needed. I don't know if the existing name needs to change if the description now accurately captures its purpose - especially if it is the variable that will be used most commonly across other rules/supplements. I'm currently somewhat opposed to increasing verbosity in the naming conventions of a calculated variable if a defined rule hasn't yet been created or conceptualized that would require having multiple different ones. This could be something to review and update in the future if we run into a situation where these two variables need to be handled very discretely?

**Comment by tekarrawilkinson** [comment]
@brysonjbest @sbuhovac 

I understand not making inputs without the need for them yet. I captured this information in the family composition gorules Feature 4937. I am good with keeping that input with its updated definition, and knowing we may have to create another input at some point. Also, once we get further into familycomposition as a topic and rule, this will impact any rules regarding familyunitsize and composition and this topic will further delved into. 

I am comfortable passing this one through as done for now, knowing it will be revisited and I have captured the concerns from this thread. If there are additional concerns or questions, let's discuss before I make any updates here in GitHub :)

**Review by sbuhovac — APPROVED** [review]
Isolation testing passed with the current inputs as they are.

[general-supplements_comforts-allowance_testing_general-supplements_comforts-allowance_2024-11-19T22-35-16Z.csv](https://github.com/user-attachments/files/17822444/general-supplements_comforts-allowance_testing_general-supplements_comforts-allowance_2024-11-19T22-35-16Z.csv)

**Review by rachel0728 — APPROVED** [review]
Testing passed as per Sasha's comment.

**Pull request merged**
