### PR TITLE
Updated example-test-rule.json

### PR DESCRIPTION
**Pull request by brysonjbest**
Adding example-test-rule.json.

Review: https://brms-simulator-dev.apps.silver.devops.gov.bc.ca/rule/66d8bf065e8212bde311c78a?version=inReview

### CODE REVIEW

**Review by sbuhovac — APPROVED** [review]
Test approval by Sasha

**Review by prchristenson — APPROVED** [review]
Amazing rule!

**Review by Iliana777 — APPROVED** [review]
Looks good to me.

**Review by tekarrawilkinson — APPROVED** [review]
great!

**Comment by brysonjbest** [comment]
@tekarrawilkinson testing comments

**Comment by prchristenson** [comment]
@rachel0728 What do you think of this rule?

**Comment by rachel0728** [comment]
I think this rule is great! @prchristenson

**Pull request closed without merging**
