### PR TITLE
Updated wintersupplement.json

### PR DESCRIPTION
**Pull request by brysonjbest**
Adding wintersupplement.json.

Review: https://brms-simulator.apps.silver.devops.gov.bc.ca/rule/d4698462-272c-4512-984d-95f1e402de2e?version=inReview

### CODE REVIEW

**Comment by tekarrawilkinson** [comment]
@sbuhovac @rachel0728 I have added the scenarios for this rule. It's ready for isolation testing.

**Review by rachel0728 — COMMENTED** [review]
@sbuhovac @prchristenson @Iliana777 Question:  Should this rule account for those who may have received it for example when it's been issued auto for dec month and then perhaps a child is added in Dec and we issue it as a one time?   OIA asks if they've received it previously.  Thanks.

**Comment by Iliana777** [comment]
@rachel0728 @sbuhovac @prchristenson Good point, Rachel. This is mentioned on sticky notes in the map but it was not included as a question. I think the rule should account for this. @tekarrawilkinson is this rule meant only to calculate the winter supplement for those who are eligible (thinking of the comforts rule that it is only for the family members going into a facility) or is it meant to establish eligibility for the supplement?

**Comment by tekarrawilkinson** [comment]
@Iliana777 @prchristenson @sbuhovac @rachel0728  This touches on something with this rule that will need a lot more discussion as Winter Supplement is a batch job. I think the best way forward is to view this rule as the batch job happy path version, without the ability to add additional family members. We will need capture details to handle the one-off rule in the future as it will apply to other supplements as well.

**Comment by Iliana777** [comment]
@tekarrawilkinson @rachel0728 @sbuhovac @prchristenson Makes sense about it being a batch job rule and that we will need another rule to issue the supplement manually.

**Comment by rachel0728** [comment]
@tekarrawilkinson @rachel0728 @sbuhovac @prchristenson would that separate rule then also apply for intake when the client would be eligible for IA and we issue it to the family unit for December?

**Comment by tekarrawilkinson** [comment]
> @tekarrawilkinson @rachel0728 @sbuhovac @prchristenson would that separate rule then also apply for intake when the client would be eligible for IA and we issue it to the family unit for December?

I will capture that manual issuance version of the rule also captures when client are found eligible in December but are not in the initial batch job. 

This rule went straight to isolation testing, once I get your approvals I will go ahead and merge this pull request. Thanks for all the input :)

**Comment by sbuhovac** [comment]
@tekarrawilkinson @prchristenson @Iliana777 

@rachel0728  and I did Isolation testing and all scenarios with single parents failed. The expected base amount is $120 and the results show $60. 
[general-supplements_wintersupplement_testing_general-supplements_wintersupplement_2024-11-21T17-17-17Z.csv](https://github.com/user-attachments/files/17849748/general-supplements_wintersupplement_testing_general-supplements_wintersupplement_2024-11-21T17-17-17Z.csv)

**Comment by tekarrawilkinson** [comment]
@sbuhovac @rachel0728 the logic has been updated to capture this. please test again and it should work as expected. Thank you! 

_side note: I am going to capture some details to put under family composition as I am aware of the category codes for Couple, One Parent Family, Single, and Two Parent family etc. and will want to update this rule (and many others) once we review family composition further, just not sure what that will look like yet._

**Comment by sbuhovac** [comment]
> @sbuhovac @rachel0728 the logic has been updated to capture this. please test again and it should work as expected. Thank you!
> 
> _side note: I am going to capture some details to put under family composition as I am aware of the category codes for Couple, One Parent Family, Single, and Two Parent family etc. and will want to update this rule (and many others) once we review family composition further, just not sure what that will look like yet._

@tekarrawilkinson 
Single parent scenarios are still showing the base amount of $60 instead of $120.

**Comment by tekarrawilkinson** [comment]
@sbuhovac 
it hadn't been pushed to in review, sorry about that. can you try it again?

**Review by sbuhovac — APPROVED** [review]
Isolation testing re-done and all tests passed.
[general-supplements_wintersupplement_testing_general-supplements_wintersupplement_2024-11-22T00-33-11Z.csv](https://github.com/user-attachments/files/17853649/general-supplements_wintersupplement_testing_general-supplements_wintersupplement_2024-11-22T00-33-11Z.csv)

**Comment by rachel0728** [comment]
Per Sasha's comment; all re-tests passed.

**Pull request merged**
